language: node_js
node_js:
  - "7"

branches:
  only:
  - master

before_script:
  - npm install -g --silent @angular/cli
  - npm install

script:
  - ng build

deploy:
  provider: azure_web_apps
  username: AZURE_WA_USER
  password: AZURE_WA_PASSWORD
  site: bomad
