language: node_js
node_js:
  - "7"

branches:
  only:
  - master

before_script:
  - npm install -g --silent @angular/cli
  - npm install
  - sudo apt-get install sshpass

script:
  - ng build
  - sshpass -p "CuaBomad16" scp -rv -o PubkeyAuthentication=no StrictHostKeyChecking=no dist/ bomad@13.92.134.14:/home/bomad
